# Generated by Django 3.0.5 on 2020-04-03 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='screen_name',
        ),
    ]
